-- ====================================================================
-- SUPABASE SQL SETUP FOR MUSIC STREAMING PLATFORM
-- ====================================================================
-- Run this entire script in your Supabase SQL Editor:
-- Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run

-- 1. Create the `songs` table
CREATE TABLE IF NOT EXISTS public.songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    album TEXT NOT NULL DEFAULT 'Single',
    cover_url TEXT NOT NULL,
    audio_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.songs ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Allow anyone (public/anon) to read all songs
CREATE POLICY "Public songs are viewable by everyone" 
ON public.songs 
FOR SELECT 
USING (true);

-- Allow anyone (public/anon) to insert songs (for simple demo/admin dashboard)
CREATE POLICY "Anyone can insert songs" 
ON public.songs 
FOR INSERT 
WITH CHECK (true);

-- Allow anyone (public/anon) to update songs
CREATE POLICY "Anyone can update songs" 
ON public.songs 
FOR UPDATE 
USING (true)
WITH CHECK (true);

-- Allow anyone (public/anon) to delete songs
CREATE POLICY "Anyone can delete songs" 
ON public.songs 
FOR DELETE 
USING (true);

-- 4. Enable Realtime (optional, allows live updates across clients)
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE public.songs;
COMMIT;

-- 5. Seed initial sample songs (Includes the user's provided Cloudinary URL)
INSERT INTO public.songs (title, artist, album, cover_url, audio_url)
VALUES 
(
    'Ey Inga Paaru', 
    'StarMusiQ Artists', 
    'Kollywood Beats', 
    'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80', 
    'https://res.cloudinary.com/tyqpilxi/video/upload/v1790314415/Ey_Inga_Paaru-StarMusiQ.Com.mp3'
),
(
    'Midnight Cyber Waves', 
    'Neon Horizon', 
    'Synthetic Dreams', 
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80', 
    'https://res.cloudinary.com/tyqpilxi/video/upload/v1790314415/Ey_Inga_Paaru-StarMusiQ.Com.mp3'
),
(
    'Aurora Nights', 
    'Starlight Orchestra', 
    'Cosmic Echoes', 
    'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80', 
    'https://res.cloudinary.com/tyqpilxi/video/upload/v1790314415/Ey_Inga_Paaru-StarMusiQ.Com.mp3'
);
